### ISSUE TITLE
Create some sort of error handling to avoid error for model without AUC

### ISSUE THREAD

**Issue by BrahimFakri** [MEDomics-UdeS/MEDomicsLab#116]

**Comment by BrahimFakri** [comment]
https://github.com/MEDomics-UdeS/MEDomicsLab/assets/119059452/38701469-93ca-4758-a18f-88a0ab3cedd5

**Comment by MahdiAll99** [comment]
Closing issue: Infinity of checks must be implemented...and the current error handling explains well the error's source.
