### ISSUE TITLE
SweetViz - Temporary files creation denied 

### ISSUE THREAD

**Issue by NicoLongfield** [MEDomics-UdeS/MEDomicsLab#182]
[Errno 13] Permission denied: '/opt/MEDomicsLab/resources/tmp'

Happens on ubuntu20.04 - cannot start the built app in sudo mode neither (it's better to let it this way)

**Comment by MahdiAll99** [comment]
Issue fixed using tempfile package and automatically generating temp files.

**Comment by MahdiAll99** [comment]
Tested on release draft v0.9.2 -> A1
