### ISSUE TITLE
Error for columns with tag as target in SweetViz module - Emily Maeusel 

### ISSUE THREAD

**Issue by mvallieres** [MEDomics-UdeS/MEDomicsLab#265]
Hello MEDomicsLab,

Below is my feedback:

Version of MEDomicsLab
MEDomicsLab-0.0.4-prealpha

Issues:
I tried using the SweetViz module for different datasets and columns.
If I select a column with an assigned tag as target the report generation results in the following error (example for new_demographic_embeddings.csv and "anchor_age" as target):

"Feature 'anchor_age' was specified as TARGET, but is NOT FOUND in the dataframe (watch case-sensitivity?)."

However, a report can be generated for the subject_id column as it has no tag.

Type:
bug

Additional comments:
Windows 10

**Comment by MahdiAll99** [comment]
Appears to be fixed for now! I tested it.
