### ISSUE TITLE
Regression with custom data file not working - Learning Module

### ISSUE THREAD

**Issue by Sari27** [MEDomics-UdeS/MEDomicsLab#277]
Probably linked to the implementation of the MEDomicsLab Standard format, we can't run pipelines with custom data files anymore.

![Image](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/48992399/3faae714-bf57-479e-9ae2-d387e4cdfeaf)

![Image](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/48992399/aa774ab7-b453-48c8-a99f-dc7e531c74d9)

**Comment by MahdiAll99** [comment]
Fixed and tested: an extra default parameter was causing the issue (the extra parameter is never used).
