### ISSUE TITLE
numeric_imputation in Clean node has True/False as input - Emily Maeusel 

### ISSUE THREAD

**Issue by mvallieres** [MEDomics-UdeS/MEDomicsLab#287]
Hello MEDomicsLab,

Below is my feedback:

Version of MEDomicsLab
MEDomicsLab-0.0.5-prealpha

Issues:
For the "numeric_imputation" in the Clean node one can choose between True and False whereas the imputation type itself needs to be entered as input. When selecting "numeric_imputation" and choosing True/False an error occurs: "Invalid value for the numeric_imputation parameter, got True. Choose from: drop, mean, median, mode, knn."

Type:
bug

Additional comments:

**Comment by MahdiAll99** [comment]
V1 release: Seems to be solved (tested on windows 10)

Will be tested on other OS.

**Comment by MahdiAll99** [comment]
False flag: Seems to be fixed, but passing true takes "mean" as an imputation method.

But it's now fixed, the numeric_imputation is a list not a bool
