### ISSUE TITLE
Create / Change DB while opening / using the app

### ISSUE THREAD

**Issue by Sari27** [MEDomics-UdeS/MEDomicsLab#294]
Like when we select a workspace or change of workspace

**Comment by Pyropingouin** [comment]
Fonctionne bien, mais garde en DB et en visuel les donnée du précédent workspace lors d'un changement. Est-ce que c'est un comportement que l'on désir conserver ?

![Image](https://github.com/user-attachments/assets/d028c6f1-ab03-4811-8d77-bf25583225ac)

![Image](https://github.com/user-attachments/assets/b8921e8c-7ffa-4908-96e6-867828faa563)
![Image](https://github.com/user-attachments/assets/bbf53f6c-0528-45c2-be94-b02877cafaac)

**Comment by Pyropingouin** [comment]
Lors d'une fermeture complète de l'app (et de l'ordinateur) nous ne retrouvons pas les traces de l'anciens workspace, ni en local ni en BD.  Peut-être qu'il faudrait faire un reset sur l'affichage lors d'un changement de Workspace ?
