### ISSUE TITLE
Implement MongoDB in Exploratory Module

### ISSUE THREAD

**Issue by Sari27** [MEDomics-UdeS/MEDomicsLab#305]
Detail list of tasks here

**Comment by Pyropingouin** [comment]
Lorsque l'on click sur exploratory Module dans la sidebar, comme il n'y a pas d'option supplémentaire (contrairement à extraction) le module exploratory ne s'ouvre pas dans une nouvelle Tab. Il faut Absolument double clicker dessus pour qu'une nouvelle tab s'ouvre. Cela est contre intuitif et il laisse croire à un bug.

Suggestions:
-soit mettre des options (comme extraction pour rester homogène)
-soit ouvrir directement une tab lorsque l'on click sur exploratory (pas recommandé, parce que comportement différents des autres modules)

**Comment by Pyropingouin** [comment]
Il faudrait tester avec un version de Pandas qui support iteritem. Mon mac n'a pas de version Pandas assez vieille qui est supporté pour l'architecture M1.  J'ai tester ydata-profiling et ça marche très bien. C'est SweetViz qui requiert une version spécifique de Pandas
