### ISSUE TITLE
Sidebar Tree functionalities

### ISSUE THREAD

**Issue by Sari27** [MEDomics-UdeS/MEDomicsLab#325]
- [x] rename
- [x] create folder : Add the folder in workspace
- [x] refresh
- [x] delete
- [x] open in
- [x] sync with local WS

**Comment by Pyropingouin** [comment]
La création de dossier ne s'effectue pas dans le local workspace. De plus, lorsqu'on click droit sur un nouveau dossier dans l'application et que l'on fait ''reveal in explorer'', l'explorateur de fichier n'ouvre pas parce que le dossier n'est pas présent. Par contre, le dossier est bien ajouter dans MongoDB

![Image](https://github.com/user-attachments/assets/549bd8e5-f045-4e0a-8557-2919ef804f42)
![Image](https://github.com/user-attachments/assets/18f2a6e0-8496-477d-95ba-c007356e0ef0)
