### ISSUE TITLE
Packager la V1

### ISSUE THREAD

**Issue by BrahimFakri** [MEDomics-UdeS/MEDomicsLab#357]
- [x] Installation popup at first boot of the app (First setup popup)
- [x] Add checks at startup of the app 
- [x] Add MongoDB and Python installations on the first setup popup
- [x] MongoDB installation - WIndows
- [x] MongoDB installation - MacOS
- [x] MongoDB installation - Linux
- [x] Python installation - Windows
- [x] Python installation - MacOS
- [x] Python installation - Linux

**Comment by MahdiAll99** [comment]
The application is now packaged, V1 is released.
