### ISSUE TITLE
README videos not working

### ISSUE THREAD

**Issue by Sari27** [MEDomics-UdeS/MEDomicsLab#57]

**Comment by BrahimFakri** [comment]
I uploaded the videos to Youtube:

Explication frontend du learning module
https://youtu.be/xTEUGd_mgiw

Explication backend du learning module
https://youtu.be/fux-MMNf2-U

They are unlisted



![Image](https://github.com/MEDomics-UdeS/MEDomicsLab/assets/119059452/d603a5b5-77d8-4ae3-af07-ad7cdf819246)

**Comment by BrahimFakri** [comment]
Already fixed
